### ISSUE TITLE
There are two make errors

### ISSUE THREAD

**Issue by EasyLuck** [HNUSystemsLab/Halo#1]
hash_api.h:20:15: error: invalid conversion from ‘const char*’ to ‘char’ [-fpermissive]
   20 |     PM_PATH = "/mnt/pmem0/hash/Halo/";
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               |
      |               const char*

/usr/include/c++/9/type_traits:2378:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::__cxx11::basic_string<char>&>’
 2378 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
make: *** [Makefile:48: HALO] Error 1

**Comment by DaokunHu** [comment]
I have fixed it, please try the new commit version.@EasyLuck
